#pragma once

// Generated bytecode will be embedded during CI build
#ifndef FLOATING_MENU_DEX_H
#define FLOATING_MENU_DEX_H

static const unsigned char classes_dex[] = {
  0x64, 0x65, 0x78, 0x0a, 0x30, 0x33, 0x35, 0x00
};
static const unsigned int classes_dex_len = sizeof(classes_dex);

#endif
